apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
  namespace: development
spec:
  selector:
    matchLabels:
      greeting: hello
      department: world
  replicas: 2
  template:
    metadata:
      labels:
        greeting: hello
        department: world
    spec:
      containers:
      - name: hello
        image: "gcr.io/google-samples/hello-app:2.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: "PORT"
          value: "50000"